class EscalasComportamento {
  static final Map<String, List<String>> perguntas = {
    'SNAP-IV (TDAH 18 Itens)': [
      '1. Não consegue prestar muita atenção a detalhes ou comete erros por descuido nos deveres escolares.',
      '2. Tem dificuldade para manter a atenção em tarefas ou atividades de lazer.',
      '3. Parece não estar ouvindo quando se fala diretamente com ele(a).',
      '4. Não segue instruções até o fim e não termina deveres de escola ou tarefas.',
      '5. Tem dificuldade para organizar tarefas e atividades.',
      '6. Evita, não gosta ou se envolve contra a vontade em tarefas que exigem esforço mental prolongado.',
      '7. Perde coisas necessárias para atividades (brinquedos, deveres, lápis, livros).',
      '8. Distrai-se facilmente com estímulos externos.',
      '9. É esquecido(a) em atividades do dia a dia.',
      '10. Remexe as mãos ou os pés ou se contorce na cadeira.',
      '11. Abandona sua cadeira em sala de aula ou em outras situações nas quais se espera que fique sentado(a).',
      '12. Corre ou escala excessivamente em situações nas quais isto é inapropriado.',
      '13. Tem dificuldade para brincar ou engajar-se silenciosamente em atividades de lazer.',
      '14. Está "a mil" ou age como se estivesse "ligado(a) a um motor".',
      '15. Fala em excesso.',
      '16. Dá respostas precipitadas antes de as perguntas terem sido completadas.',
      '17. Tem dificuldade para esperar sua vez.',
      '18. Interrompe os outros ou se intromete (conversas, jogos).'
    ],
    'Escala Conners (10 Perguntas)': [
      '1. É inquieto(a), hiperativo(a), está sempre em movimento.',
      '2. É excitável, impulsivo(a).',
      '3. Incomoda outras crianças ou perturba atividades alheias.',
      '4. Não termina o que começa (pouca concentração).',
      '5. Vive dando de ombros, se contorcendo ou remexendo.',
      '6. É desatento(a), distrai-se facilmente.',
      '7. Exigências devem ser satisfeitas imediatamente (frustra-se fácil).',
      '8. Chora fácil ou com frequência.',
      '9. Muda de humor rapidamente (instabilidade emocional).',
      '10. Apresenta explosões de raiva ou comportamento imprevisível.'
    ],
    'Escala Basic 3 (12 Perguntas)': [
      '1. Apresenta comportamento desafiador ou opositor diante de figuras de autoridade.',
      '2. Tem dificuldades em seguir regras básicas estabelecidas em grupo.',
      '3. Demonstra agressividade verbal ou física ao ser contrariado(a).',
      '4. Apresenta episódios frequentes de mentiras ou omissões sobre seus atos.',
      '5. Danifica materiais próprios ou de colegas intencionalmente.',
      '6. Tem dificuldade em aceitar consequências e punições de forma madura.',
      '7. Isola-se ou recusa cooperação em atividades de equipe.',
      '8. Apresenta inquietação e impaciência severa durante explicações.',
      '9. Culpa os outros por seus próprios erros ou mau comportamento.',
      '10. É facilmente irritável por atitudes banais de terceiros.',
      '11. Demonstra falta de empatia ou remorso após um conflito.',
      '12. Apresenta resistência severa em iniciar tarefas propostas.'
    ],
    // 1. ESCALA ICU COMPLETA (24 perguntas)
    'Escala ICU (Traços Insensíveis e Frios)': [
      '1. Expressa sentimentos abertamente quando algo acontece?',
      '2. Sente-se mal ou culpado(a) quando faz algo errado?',
      '3. Preocupa-se em ter um bom desempenho na escola ou tarefas?',
      '4. Demonstra pouca preocupação com os sentimentos dos outros?',
      '5. É superficial ou esconde o que realmente sente?',
      '6. Preocupa-se em machucar ou magoar os sentimentos de alguém?',
      '7. Defende ou apoia amigos que estão passando por problemas?',
      '8. Importa-se se é visto(a) como alguém frio(a) ou insensível?',
      '9. Demonstra arrependimento genuíno após uma briga ou discussão?',
      '10. Coloca-se no lugar dos outros para entender suas dores?',
      '11. Importa-se com o impacto de suas ações no bem-estar alheio?',
      '12. Esconde suas emoções para não parecer vulnerável?',
      '13. Parece não se importar com punições ou advertências recebidas?',
      '14. Mostra-se indiferente ao sofrimento de animais ou pessoas?',
      '15. É carinhoso(a) com familiares e pessoas próximas?',
      '16. Evita pedir desculpas mesmo sabendo que errou?',
      '17. Age com egoísmo em situações de partilha ou grupo?',
      '18. Demonstra frieza emocional em momentos de alta tensão?',
      '19. Minimiza a importância de regras sociais ou familiares?',
      '20. Parece não sentir remorso por quebrar promessas?',
      '21. Valoriza a honestidade nas suas relações diárias?',
      '22. Mostra indiferença quando alguém chora por perto?',
      '23. Tenta consertar os erros que comete com os amigos?',
      '24. Mantém uma postura distante mesmo com pessoas queridas?',
    ],
    // 2. ESCALA CRIES-13 COMPLETA (13 perguntas)
    'Escala CRIES-13 (Estresse Pós-Traumático)': [
      '1. Pensa no evento traumático mesmo sem querer ou sem intenção?',
      '2. Tenta evitar conversas ou lembranças que recordem o ocorrido?',
      '3. Tem ondas de sentimentos ou imagens fortes sobre o evento?',
      '4. Fica muito vigilante, assustado(a) ou pulando por qualquer barulho?',
      '5. Tem sonhos ou pesadelos recorrentes com o que aconteceu?',
      '6. Evita lugares, pessoas ou situações que lembrem o trauma?',
      '7. Sente-se como se estivesse vivendo o momento ruim novamente?',
      '8. Tem dificuldade para se concentrar nas aulas ou leituras?',
      '9. Evita pensamentos ou sentimentos internos ligados ao ocorrido?',
      '10. Apresenta reações físicas fortes (suor, batimentos rápidos) ao lembrar?',
      '11. Sente-se isolado(a) ou distante de amigos e familiares desde então?',
      '12. Tem crises de choro ou irritação sem um motivo aparente associado?',
      '13. Apresenta problemas ou sobressaltos para pegar no sono?',
    ],
    // 3. ESCALA IAT COMPLETA (10 perguntas)
    'Escala IAT (Dependência de Internet)': [
      '1. Permanece conectado(a) online por mais tempo do que pretendia?',
      '2. Negligencia tarefas escolares ou de rotina para passar mais tempo na rede?',
      '3. Prefere o entusiasmo ou interação digital às saídas com amigos?',
      '4. Forma novos relacionamentos ou vínculos significativos com usuários online?',
      '5. Pessoas próximas reclamam do seu tempo excessivo de tela?',
      '6. Seu rendimento ou notas escolares caíram devido ao uso da internet?',
      '7. Checa mensagens ou redes antes de realizar qualquer atividade essencial?',
      '8. Sente-se deprimido(a), irritado(a) ou nervoso(a) quando fica offline?',
      '9. Bloqueia ou esconde de familiares o que faz ou assiste online?',
      '10. Perde horas de sono ou descanso saudável para continuar navegando?',
    ],
    // 4. ESCALA MBI COMPLETA (10 perguntas adaptadas)
    'Escala MBI (Inventário de Burnout)': [
      '1. Sente-se emocionalmente exausto(a) ou esgotado(a) com a rotina de estudos ou trabalho?',
      '2. Sente-se cansado(a) logo ao acordar e precisar enfrentar mais um dia de atividades?',
      '3. Tem a sensação de que o esforço diário não gera resultados ou reconhecimento?',
      '4. Demonstra distanciamento, frieza ou menos interesse pelos colegas e professores?',
      '5. Sente-se mais cínico(a) ou pessimista em relação ao futuro das suas tarefas?',
      '6. Falta-lhe energia ou disposição física para se engajar em projetos novos?',
      '7. Sente que as demandas diárias superam a sua capacidade de enfrentamento?',
      '8. Apresenta irritabilidade excessiva com pequenas cobranças da rotina?',
      '9. Sente que a sua produtividade despencou significativamente nas últimas semanas?',
      '10. Sente-se frustrado(a) ou sem propósito ao realizar suas obrigações diárias?',
    ],

    // 5. ESCALA CFQ COMPLETA (10 perguntas de Falhas Cognitivas)
    'Escala CFQ (Falhas Cognitivas)': [
      '1. Esquece o que pretendia fazer ou buscar logo após entrar em um cômodo?',
      '2. Deixa de notar placas de trânsito, avisos ou caminhos que conhece bem?',
      '3. Esquece onde guardou objetos comuns de uso diário (chaves, carteira, óculos)?',
      '4. Tem a sensação de que as palavras ficam "na ponta da língua", mas não consegue lembrá-las?',
      '5. Distrai-se facilmente durante leituras simples e precisa reler o mesmo parágrafo?',
      '6. Entra em uma sala e esquece completamente o motivo pelo qual foi até lá?',
      '7. Esquece compromissos, datas importantes ou recados que prometeu dar?',
      '8. Tem dificuldade em manter o fio da meada em conversas longas ou explicações?',
      '9. Comete erros por distração em tarefas manuais corriqueiras da rotina?',
      '10. Sente que sua mente "desliga" por alguns segundos em meio a uma atividade?',
    ],

    // 6. ESCALA MSI-BPD COMPLETA (10 perguntas Borderline)
    'Escala MSI-BPD (Traços de Personalidade)': [
      '1. Apresenta oscilações de humor extremas e repentinas no mesmo dia (ex: vai da alegria à raiva)?',
      '2. Nutre um medo crônico, intenso e desesperado de ser abandonado(a) por amigos ou parceiros?',
      '3. Seus relacionamentos costumam ser tempestuosos, alternando entre idealização e desvalorização?',
      '4. Apresenta episódios de raiva intensa, inadequada e de difícil controle?',
      '5. Tem uma sensação persistente de vazio interno ou de não saber quem realmente é?',
      '6. Age por impulso em áreas prejudiciais (compras, direção, alimentação, abuso de substâncias)?',
      '7. Já apresentou comportamentos, ameaças ou ideações de autoflagelação em momentos de crise?',
      '8. Desenvolve pensamentos paranóicos temporários ou desconfiança extrema sob estresse?',
      '9. Sente-se frequentemente rejeitado(a) ou injustiçado(a) pelas pessoas mais próximas?',
      '10. Tem dificuldade em estabelecer limites saudáveis e estáveis nos seus vínculos afetivos?',
    ],
    // 7. ESCALA CRAFFT 2.1 COMPLETA (6 perguntas)
    'Escala CRAFFT 2.1 (Rastreio de Substâncias)': [
      '1. Já andou em um carro dirigido por alguém (ou por você) que estava sob efeito de álcool ou drogas?',
      '2. Usa álcool ou drogas para relaxar, se sentir melhor consigo mesmo ou se integrar a um grupo?',
      '3. Usa álcool ou drogas enquanto está sozinho(a) ou isolado(a)?',
      '4. Esquece frequentemente de coisas que fez enquanto usava álcool ou drogas?',
      '5. Familiares ou amigos já disseram que você deveria diminuir o uso de álcool ou drogas?',
      '6. Já se meteu em problemas ou confusões enquanto estava usando álcool ou drogas?',
    ],

    // 8. CHECKLIST DE VITIMIZAÇÃO E CONVIVÊNCIA ESCOLAR - BULLYING (10 perguntas)
    'Checklist de Vitimização (Bullying)': [
      '1. Sofre com apelidos ofensivos, xingamentos ou piadas humilhantes de forma repetida no ambiente escolar?',
      '2. É excluído(a), isolado(a) ou ignorado(a) de propósito por colegas em atividades ou grupos?',
      '3. É alvo de boatos, fofocas ou mentiras espalhadas para prejudicar sua reputação?',
      '4. Já sofreu agressões físicas (empurrões, tapas, socos) ou ameaças por parte de outros alunos?',
      '5. Teve pertences pessoais (material, roupas, lanche) danificados, roubados ou escondidos por colegas?',
      '6. Recebe mensagens ofensivas, ameaças ou piadas humilhantes através de redes sociais ou celular (Cyberbullying)?',
      '7. Sente medo, ansiedade ou insegurança em determinados locais da escola (banheiros, pátio, corredores)?',
      '8. Apresenta resistência, desculpas ou recusa frequente em ir à escola por medo do tratamento dos colegas?',
      '9. Sente que os professores ou inspetores não percebem ou não conseguem conter as situações de humilhação?',
      '10. Nota mudanças repentinas no seu humor, choro fácil ou isolamento após retornar do ambiente escolar?',
    ],
    // 9. INVENTÁRIO BIG FIVE REDUZIDO (15 perguntas)
    'Inventário Big Five (Personalidade)': [
      '1. É alguém extrovertido(a), comunicativo(a) e que recarrega as energias interagindo com pessoas?',
      '2. Tende a ser crítico(a), questionador(a) ou a entrar em debates acalorados com facilidade?',
      '3. É altamente organizado(a), confiável, focado(a) e cumpre seus prazos com rigor?',
      '4. Fica ansioso(a), preocupado(a) ou desestabiliza-se emocionalmente com facilidade diante de estresse?',
      '5. Tem grande interesse por conceitos abstratos, arte, novas ideias e experiências originais?',
      '6. Prefere a calmaria, ambientes reservados e costuma ser mais calado(a) ou introspectivo(a)?',
      '7. É uma pessoa empática, inclinada a confiar nos outros e a ajudar de forma altruísta?',
      '8. Age de forma descuidada, desorganizada ou procrastina tarefas importantes com frequência?',
      '9. É emocionalmente estável, mantendo a calma e resiliência mesmo em momentos de crise?',
      '10. Prefere rotinas previsíveis, tarefas práticas e tem pouca abertura para mudanças drásticas?',
      '11. Toma a iniciativa em grupos e assume papéis de liderança com naturalidade?',
      '12. Tende a ser desconfiado(a) ou prefere manter um pé atrás com intenções alheias?',
      '13. É focado(a) na autodisciplina e resiste bem a distrações para atingir um objetivo de longo prazo?',
      '14. Sofre com oscilações frequentes de humor e ruminações sobre problemas passados?',
      '15. Tem uma imaginação ativa e gosta de buscar soluções criativas e fora do padrão para os problemas?',
    ],
  };
}
