class EscalasAdulto {
  static const Map<String, List<String>> perguntas = {
    // === 1. ASRS-18 COMPLETA (18 perguntas oficiais da OMS para TDAH Adulto) ===
    'ASRS-18 Completa (TDAH Adulto)': [
      '1. Com que frequência você tem dificuldade para finalizar os detalhes finais de um projeto, após as partes mais difíceis terem sido feitas?',
      '2. Com que frequência você tem dificuldade para colocar as coisas em ordem quando está organizando uma tarefa ou trabalho?',
      '3. Com que frequência você tem dificuldade para lembrar de compromissos ou obrigações?',
      '4. Quando você tem uma tarefa que exige muito esforço mental, com que frequência você evita ou adia o início?',
      '5. Com que frequência você fica remexendo as mãos ou os pés ou se contorcendo na cadeira quando precisa permanecer sentado?',
      '6. Com que frequência você se sente ativo demais ou forçado a fazer coisas, como se estivesse movido por um motor?',
      '7. Com que frequência você comete erros por falta de atenção quando trabalha em um projeto chato ou difícil?',
      '8. Com que frequência você tem dificuldade para manter a atenção quando está fazendo um trabalho chato ou repetitivo?',
      '9. Com que frequência você tem dificuldade para se concentrar no que as pessoas dizem, mesmo quando estão falando diretamente com você?',
      '10. Com que frequência você perde ou tem dificuldade para encontrar coisas em casa ou no trabalho?',
      '11. Com que frequência você se distrai com estímulos ou barulhos ao seu redor?',
      '12. Com que frequência você sai da sua cadeira em reuniões ou em outras situações em que deveria ficar sentado?',
      '13. Com que frequência você se sente inquieto ou agitado por dentro?',
      '14. Com que frequência você tem dificuldade para sossegar e relaxar quando tem tempo livre para você?',
      '15. Com que frequência você se pega falando demais em situações sociais?',
      '16. Quando alguém está falando com você, com que frequência você termina as frases da pessoa antes que ela mesma termine?',
      '17. Com que frequência você tem dificuldade para esperar a sua vez em situações em que isso é exigido?',
      '18. Com que frequência você interrompe os outros quando eles estão ocupados ou conversando?',
    ],

    // === 2. DISLEXIA ADULTO COMPLETA (10 perguntas) ===
    'Dislexia Adulto (Checklist Completo)': [
      '1. Você confunde ou pula linhas com frequência durante a leitura silenciosa de textos longos?',
      '2. Sente que lê de forma visivelmente mais lenta do que a média dos seus colegas de trabalho ou estudo?',
      '3. Sente grande dificuldade ou desconforto quando precisa preencher formulários oficiais ou contratos?',
      '4. Costuma cometer erros ortográficos insistentes mesmo em palavras simples do cotidiano?',
      '5. Tem dificuldade crônica para memorizar recados, números de telefone ou instruções faladas rapidamente?',
      '6. Evita situações profissionais ou acadêmicas que exijam a leitura de relatórios em público?',
      '7. Confunde sequências lógicas cotidianas, como ordens de meses, números ou direções (esquerda/direita)?',
      '8. Sente fadiga mental extrema, dores de cabeça ou cansaço visual após curtos períodos de leitura?',
      '9. Tem dificuldade em compreender ou reter o sentido profundo de textos complexos na primeira leitura?',
      '10. Sente que sua escrita não acompanha a velocidade e a clareza dos seus pensamentos?',
    ],
    // === 3. ESCALA AQ-10 COMPLETA (10 perguntas oficiais - Autismo Adulto Inicial) ===
    'Escala AQ-10 Completa (Autismo Adulto)': [
      '1. Eu noto sons suaves com facilidade enquanto outras pessoas parecem não perceber nada.',
      '2. Eu costumo focar mais na imagem como um todo do que nos pequenos detalhes de uma situação.',
      '3. Acho fácil realizar mais de uma atividade mental ou tarefa ao mesmo tempo.',
      '4. Se houver uma interrupção, consigo retornar à minha tarefa de forma rápida e sem estresse.',
      '5. Acho fácil ver nas entrelinhas ou captar ironias quando alguém conversa comigo.',
      '6. Consigo perceber com facilidade se a pessoa com quem converso está entediada ou cansada.',
      '7. Quando leio uma história, acho difícil imaginar como os personagens se parecem fisicamente.',
      '8. Gosto de coletar informações detalhadas sobre categorias de coisas ou temas específicos.',
      '9. Acho fácil descobrir o que alguém está sentindo apenas olhando para as expressões do rosto.',
      '10. Frequentemente tenho dificuldade em entender as reais intenções das pessoas.',
    ],

    // === 4. ESCALA DE BURNOUT DE FREUDENBERGER (10 perguntas - Esgotamento EJA) ===
    'Escala de Burnout de Freudenberger': [
      '1. Sente-se exausto(a) física e mentalmente devido à tripla jornada (trabalho, casa e estudos)?',
      '2. Percebe que sua paciência com colegas, professores ou familiares diminuiu drasticamente?',
      '3. Sente dores físicas psicossomáticas frequentes, como dores de cabeça, estômago ou tensão muscular?',
      '4. Tem a sensação constante de que, por mais que se esforce, nunca dá conta de todas as demandas?',
      '5. Apresenta dificuldades crônicas de sono (insônia ou cansaço mesmo após dormir horas)?',
      '6. Sente que perdeu o entusiasmo ou o propósito real nas suas atividades diárias?',
      '7. Tem episódios frequentes de esquecimento ou lapsos de memória por sobrecarga mental?',
      '8. Isola-se socialmente ou evita conversas por falta de energia emocional para interagir?',
      '9. Percebe um aumento significativo na irritabilidade ou choro fácil diante de pequenos imprevistos?',
      '10. Sente que sua produtividade e concentração despencaram nas últimas semanas?',
    ],

    // === 5. INVENTÁRIO DE DEPRESSÃO DE BECK - BDI (10 perguntas adaptadas) ===
    'Inventário de Depressão de Beck (BDI)': [
      '1. Sinto-me triste, desanimado(a) ou melancólico(a) na maior parte dos meus dias.',
      '2. Olho para o futuro com desespero, sentindo que as coisas tendem a piorar ou não mudar.',
      '3. Sinto-me como um fracasso ou que decepcionei as expectativas das pessoas que amo.',
      '4. Perdi quase todo o prazer ou interesse pelas atividades e hobbies que antes eu adorava.',
      '5. Nutro sentimentos crônicos de culpa, autoacusação ou decepção com minhas escolhas.',
      '6. Sinto uma irritabilidade constante e dificuldade em tolerar pequenas falhas alheias.',
      '7. Tenho enorme dificuldade ou indecisão para tomar resoluções simples do cotidiano.',
      '8. Sinto alterações severas no meu padrão de sono (insônia severa ou hipersonia por desânimo).',
      '9. Apresenta fadiga crônica, falta de energia física ou sensação de corpo pesado.',
      '10. Percebi mudanças drásticas no meu apetite (perda total de interesse em comer ou comer por ansiedade).',
    ],
    // === 6. TAS-20 COMPLETA (20 perguntas - Escala de Alexitimia de Toronto) ===
    'TAS-20 Completa (Alexitimia)': [
      '1. Frequentemente fico confuso(a) sobre qual emoção estou sentindo por dentro.',
      '2. É difícil para mim encontrar as palavras certas para descrever meus sentimentos.',
      '3. Tenho sensações físicas e corporais que nem os médicos conseguem compreender bem.',
      '4. Sou capaz de descrever meus sentimentos com facilidade para os meus amigos e familiares.',
      '5. Prefiro analisar os problemas práticos do dia a dia em vez de ficar pensando em sentimentos.',
      '6. Quando fico chateado(a) ou triste, não sei se estou com raiva, com medo ou apenas magoado(a).',
      '7. Muitas vezes fico intrigado(a) ou sem entender as reações do meu próprio corpo.',
      '8. Prefiro deixar as coisas acontecerem naturalmente do que tentar entender por que aconteceram.',
      '9. Tenho sentimentos e emoções dentro de mim que eu simplesmente não consigo identificar.',
      '10. Conversar com as pessoas sobre os sentimentos delas é algo que considero muito importante.',
      '11. É difícil para mim saber o que se passa no íntimo das pessoas mais próximas.',
      '12. As pessoas muitas vezes me pedem para falar mais sobre os meus sentimentos e o que estou pensando.',
      '13. Não sei exatamente o que está acontecendo por dentro de mim quando me sinto tenso(a).',
      '14. Prefiro assistir a um movie de ação ou prático do que a um drama psicológico profundo.',
      '15. Tendo a me aproximar das pessoas mais por interesses práticos do que por conexões emocionais.',
      '16. Sinto-me emocionalmente ligado(a) aos meus amigos, mesmo sem precisar falar sobre isso.',
      '17. Examinar meus sentimentos internos é algo que considero uma perda de tempo ou desnecessário.',
      '18. Sinto dificuldade crônica em compreender as piadas de duplo sentido ou metáforas emocionais.',
      '19. Prefiro focar nas obrigações externas do cotidiano para não ter que lidar com minhas próprias crises.',
      '20. Ser compreendido(a) emocionalmente pelos outros é algo que raramente acontece comigo.',
    ],

    // === 7. CAT-Q COMPLETA (25 perguntas oficiais - Camuflagem Social no Autismo Adulto) ===
    'CAT-Q Completa (Camuflagem Autística)': [
      '1. Em situações sociais, eu copio ativamente os gestos, expressões e a linguagem corporal de pessoas populares.',
      '2. Eu preparo e ensaio piadas, histórias ou frases com antecedência para usar em conversas futuras.',
      '3. Eu monitoro conscientemente o meu contato visual para garantir que não pareça estranho ou excessivo para o outro.',
      '4. Eu me forço a sorrir ou demonstrar interesse mesmo quando o assunto da conversa me deixa entediado(a).',
      '5. Sinto que estou interpretando um personagem de teatro ou vestindo uma máscara quando interajo em público.',
      '6. Eu gasto muita energia mental tentando adivinhar o que as pessoas esperam que eu sinta ou faça.',
      '7. Eu pesquiso regras sociais, etiqueta ou comportamento de grupos na internet ou em livros para tentar me encaixar.',
      '8. Eu repito mentalmente o que vou falar antes de abrir a boca para evitar cometer erros sociais.',
      '9. Eu imito o estilo de roupa, corte de cabelo ou o jeito de falar de pessoas que considero bem-sucedidas socialmente.',
      '10. Sinto um esgotamento físico e mental extremo logo após passar algumas poucas horas em eventos sociais.',
      '11. Eu evito falar sobre os meus interesses especiais intensos para não parecer estranho(a) aos olhos dos outros.',
      '12. Eu monitoro o tom da minha própria voz para garantir que não pareça monótona ou robótica durante o diálogo.',
      '13. Se eu não me policiar o tempo todo, acabo quebrando regras de conversação (como interromper ou falar alto demais).',
      '14. Eu costumo me esconder em banheiros ou locais isolados durante festas para descansar da sobrecarga social.',
      '15. Eu aprendi a sorrir com os olhos olhando fixamente para o espaço entre as sobrancelhas da pessoa com quem converso.',
      '16. Eu sinto que as interações sociais nunca fluem de forma natural para mim; tudo exige cálculo e esforço planejado.',
      '17. Eu fico repassando conversas antigas na minha mente por dias, procurando por erros sociais que possa ter cometido.',
      '18. Eu uso frases prontas ou expressões idiomáticas coletadas de filmes e séries para responder às pessoas no cotidiano.',
      '19. Eu tenho dificuldade crônica em saber quando é a minha vez de falar em uma roda de conversas.',
      '20. Eu me sinto muito mais confortável interagindo por mensagens de texto do que conversando cara a cara.',
      '21. Eu mudo de personalidade ou comportamento dependendo do grupo social em que estou inserido(a).',
      '22. Eu pratico expressões faciais e sorrisos na frente do espelho para usar em interações públicas reais.',
      '23. Sinto que las pessoas só gostam da versão artificial de mim que eu apresento externamente.',
      '24. Eu me sinto um(a) impostor(a) quando sou elogiado(a) por minhas habilidades de comunicação social.',
      '25. Eu preciso de dias de isolamento e silêncio total para me recuperar após uma semana de trabalho ou estudos em grupo.',
    ],
    // === 8. ESCALA AQ-50 COMPLETA (50 perguntas oficiais - Autismo Adulto) ===
    'Escala AQ-50 Completa (Autismo Adulto)': [
      '1. Eu prefiro fazer coisas com outras pessoas do que sozinho(a).',
      '2. Eu prefiro fazer as coisas da mesma maneira, repetidamente.',
      '3. Se eu tentar imaginar algo, acho muito fácil criar uma imagem na minha mente.',
      '4. Frequentemente fico tão concentrado(a) em uma coisa que perco a noção de tudo ao redor.',
      '5. Frequentemente noto sons suaves que outras pessoas não conseguem perceber.',
      '6. Eu costumo notar números de placas de carros ou sequências de informações parecidas.',
      '7. Eu frequentemente acho difícil entender as intenções das pessoas in uma conversa.',
      '8. Eu acho fácil ler nas entrelinhas quando alguém está falando comigo.',
      '9. Eu acho fácil descobrir o que alguém está sentindo apenas olhando para o rosto da pessoa.',
      '10. Eu acho difícil fazer novos amigos ou iniciar conversas com desconhecidos.',
      '11. Eu noto padrões repetitivos ou detalhes em coisas cotidianas com muita facilidade.',
      '12. Eu prefiro ler livros de ficção e histórias do que livros de fatos reais ou técnicos.',
      '13. Para mim, é difícil me colocar no lugar de outra pessoa para entender seu ponto de vista.',
      '14. Eu tenho facilidade em manter uma conversa social leve e sem rumo (jogar conversa fora).',
      '15. Em um grupo social, eu consigo acompanhar facilmente as conversas de várias pessoas.',
      '16. Eu acho fácil descobrir o que as pessoas estão pensando ou sentindo no íntimo.',
      '17. Eu prefiro ir a uma biblioteca ou museu do que a uma festa barulhenta.',
      '18. Eu acho difícil planejar atividades ou passeios com muitas etapas organizadas.',
      '19. Eu gosto de colecionar informações sobre categorias de coisas (ex: tipos de carros, plantas).',
      '20. Eu acho fácil entender piadas, ironias ou metáforas que as pessoas usam.',
      '21. Eu frequentemente noto que as pessoas me acham rude ou insensível, sem que eu queira.',
      '22. Eu acho fascinante memorizar datas históricas, números de telefone ou estatísticas.',
      '23. Eu prefiro ambientes e rotinas previsíveis e sinto grande desconforto com mudanças repentinas.',
      '24. Eu acho fácil manter o foco em tarefas repetitivas ou detalhadas por longos períodos.',
      '25. Eu costumo focar nos pequenos detalhes de uma situação antes de enxergar o contexto geral.',
      '26. Eu prefiro manter meus hobbies e interesses para mim mesmo(a) em vez de compartilhá-los.',
      '27. Eu acho difícil interagir com pessoas da minha idade de forma natural.',
      '28. Eu acho fácil inventar histórias ou imaginar situações fictícias na minha cabeça.',
      '29. Eu tenho dificuldade em saber quando é a minha vez de falar em um diálogo.',
      '30. Eu frequentemente fico focado(a) em tópicos ou interesses muito específicos e intensos.',
      '31. Eu acho fácil ler as expressões faciais e a linguagem corporal das pessoas.',
      '32. Eu prefiro assistir a documentários científicos do que a filmes de romance ou drama.',
      '33. Eu acho difícil manter o contato visual direto com as pessoas enquanto converso.',
      '34. Eu sou muito bom(a) em notar pequenos erros ou inconsistências em textos ou tabelas.',
      '35. Eu acho difícil mentir ou inventar desculpas sociais para agradar os outros.',
      '36. Eu prefiro a solidão ou a companhia de poucos amigos íntimos no meu dia a dia.',
      '37. Eu acho fácil me adaptar a imprevistos ou mudanças de planos na rotina diária.',
      '38. Eu frequentemente me pego imitando ou copiando o jeito de falar de personagens ou pessoas.',
      '39. Eu acho difícil compreender as regras não escritas de convivência em grupo.',
      '40. Eu gosto de organizar meus objetos de uso diário em ordens muito específicas (ex: por cor, tamanho).',
      '41. Eu acho fácil manter a concentração mesmo em salas barulhentas ou com muitos estímulos.',
      '42. Eu frequentemente tenho reações intensas de incômodo com certas texturas, luzes ou tecidos.',
      '43. Eu tenho dificuldade em manter o fio da meada em conversas longas ou explicações complexas.',
      '44. Eu prefiro atividades práticas e manuais do que discussões teóricas abstratas.',
      '45. Eu costumo levar as palavras das pessoas ao pé da letra (sentido literal).',
      '46. Eu acho fascinante observar engrenagens, mapas, horários ou sistemas lógicos.',
      '47. Eu frequentemente sinto que sou um(a) observador(a) externo(a) do comportamento humano.',
      '48. Eu acho difícil manter amizades de longo prazo sem que exija um esforço exaustivo.',
      '49. Eu prefiro ler textos informativos na internet do que interagir em redes sociais.',
      '50. Eu acho fácil decifrar o que as pessoas esperam de mim em um ambiente profissional ou escolar.',
    ],
    // === 9. ESCALA GQ-ASC COMPLETA (25 perguntas - Foco em Autismo Feminino) ===
    'Escala GQ-ASC Completa (Autismo Feminino)': [
      '1. Eu sinto que minhas amizades na infância e adolescência eram mantidas porque eu copiava o comportamento de outras meninas.',
      '2. Eu costumo colecionar objetos baseados na estética, textura ou cores, mais do que pela utilidade prática.',
      '3. Eu prefiro a companhia de animais de estimação ou de pessoas muito mais velhas/mais novas do que de pessoas da minha idade.',
      '4. Eu gasto muito tempo escolhendo roupas que não incomodem minha pele, mesmo que não estejam na moda.',
      '5. Eu costumo camuflar minhas dificuldades sociais sendo excessivamente prestativa ou quieta em grupo.',
      '6. Tenho um interesse profundo e obsessivo por psicologia, comportamento humano ou biografias de pessoas.',
      '7. Sinto que consigo ser muito expressiva e comunicativa no trabalho/escola, mas desabo de cansaço ao chegar em casa.',
      '8. Eu costumo fantasiar ou criar mundos internos complexos para escapar da realidade do caderno.',
      '9. Tenho forte tendência a acumular materiais de artesanato, livros ou cadernos que raramente chego a usar por completo.',
      '10. Eu me sinto extremamente desconfortável em ambientes com luzes fluorescentes ou muitos barulhos sobrepostos.',
      '11. Eu prefiro interações sociais individuais (um a um) do que participar de grandes rodas de conversa ou festas.',
      '12. Eu costumo adotar os hobbies, gostos musicais ou o estilo de vida dos meus parceiros ou amigos mais próximos.',
      '13. Eu tenho reações emocionais muito intensas (como choro ou crises) diante de mudanças pequenas na minha rotina diária.',
      '14. Sinto que preciso "ensaiar" minhas expressões faciais e sorrisos diante do espelho para parecer simpática.',
      '15. Eu prefiro focar em tarefas minuciosas ou organizativas do que liderar ou coordenar equipes de trabalho.',
      '16. Eu frequentemente levo as piadas ou comentários das pessoas de forma literal e acabo me sentindo magoada.',
      '17. Eu tenho o hábito de roer unhas, mexer no cabelo ou balançar os pés constantemente para me acalmar (autorregulação).',
      '18. Eu sinto que passei a vida inteira interpretando um papel que não condiz com quem eu realmente sou por dentro.',
      '19. Eu tenho dificuldade crônica em expressar verbalmente o que estou sentindo em momentos de forte estresse emocional.',
      '20. Eu costumo focar obsessivamente em um único assunto por meses até esgotá-lo por completo e passar para outro.',
      '21. Eu me sinto profundamente exausta após realizar atividades corriqueiras como ir ao supermercado ou banco.',
      '22. Eu prefiro rotinas totalmente previsíveis e sinto forte ansiedade se alguém quebra um compromisso em cima da hora.',
      '23. Eu tenho dificuldade em perceber quando uma pessoa está sendo falsa, irônica ou tentando tirar vantagem de mim.',
      '24. Eu sou extremamente sensível a críticas, interpretando pequenas correções como rejeição total ao meu valor.',
      '25. Eu preciso de longos períodos de isolamento em um quarto escuro e silencioso para recuperar minhas energias cotidianas.',
    ],

    // === 10. ESCALA SRS-2 ADULTO COMPLETA (20 perguntas - Responsividade Social) ===
    'Escala SRS-2 Completa (Responsividade Social)': [
      '1. Eu tenho dificuldade em perceber o impacto do meu comportamento no humor das pessoas ao meu redor.',
      '2. Eu costumo evitar o contato visual direto com as pessoas durante um diálogo importante.',
      '3. Eu fico muito tenso(a) ou ansioso(a) em situações sociais que fogem do meu controle.',
      '4. Eu tenho dificuldade em expressar minhas emoções de forma que as outras pessoas consigam compreender.',
      '5. Eu costumo levar as conversas muito ao pé da letra, perdendo o sentido de piadas ou ironias.',
      '6. Eu prefiro focar nos meus próprios interesses em vez de participar de conversas de interesse geral.',
      '7. Eu tenho dificuldade em fazer novos amigos ou me integrar a novos grupos sociais.',
      '8. Eu me sinto desconfortável quando as pessoas se aproximam muito fisicamente de mim.',
      '9. Eu costumo repetir os mesmos assuntos ou frases de forma jinsistente durante uma conversa.',
      '10. Eu tenho dificuldade em entender o ponto de vista de outra pessoa quando ele diverge do meu.',
      '11. Eu me sinto muito mais confortável interagindo com computadores ou telas do que com pessoas.',
      '12. Eu costumo reagir de forma exagerada ou irritada a pequenos imprevistos na rotina diária.',
      '13. Eu tenho dificuldade em manter o fio da meada em diálogos longos ou dinâmicas de grupo.',
      '14. Eu prefiro realizar minhas atividades de forma isolada do que depender do ritmo de trabalho de outros.',
      '15. Eu sinto que as pessoas me acham distante, frio(a) ou desinteressado(a) in interações sociais.',
      '16. Eu tenho dificuldade em iniciar conversas com pessoas que eu não conheço muito bem.',
      '17. Eu costumo me fixar em detalhes minuciosos de objetos ou situações, perdendo o contexto geral.',
      '18. Eu me sinto sobrecarregado(a) mentalmente em locais com muitos estímulos visuais ou auditivos.',
      '19. Eu tenho dificuldade em perceber quando alguém está tentando puxar assunto ou flertar comigo.',
      '20. Eu prefiro ambientes totalmente silenciosos e isolados para conseguir focar em qualquer tarefa.',
    ],

    // === 11. ESCALA SPM-2 ADULTO COMPLETA (15 perguntas - Processamento Sensorial) ===
    'Escala SPM-2 Adulto (Sensorial)': [
      '1. Fico extremamente incomodado(a) ou irritado(a) com ruídos de fundo (como ventiladores, relógios ou trânsito).',
      '2. Detesto ou evito tocar em certas substâncias ou texturas (como argila, areia, cola ou alimentos úmidos).',
      '3. Sinto forte aversão a luzes muito brilhantes, piscantes ou ambientes com iluminação fluorescente comercial.',
      '4. Evito ou sinto náuseas com cheiros comuns do dia a dia (como perfumes, produtos de limpeza ou certos alimentos).',
      '5. Tenho reações intensas de incômodo com etiquetas de roupas, costuras de meias ou tecidos sintéticos rígidos.',
      '6. Fico facilmente tonto(a) ou enjoado(a) em movimentos simples, como andar de carro, elevador ou balanços.',
      '7. Costumo trombar em móveis, portas ou pessoas com frequência devido a uma aparente falta de equilíbrio espacial.',
      '8. Sinto necessidade constante de tocar em objetos, texturas ou superfícies ao meu redor para me autorregular.',
      '9. Tenho dificuldade crônica em ignorar estímulos visuais ao meu redor para conseguir focar em uma leitura.',
      '10. Sinto que escuto barulhos que mais ninguém na sala parece notar ou se importar.',
      '11. Detesto que me toquem de surpresa ou de forma leve, preferindo abraços ou apertos firmes.',
      '12. Apresento forte seletividade alimentar baseada estritamente na textura ou temperatura do alimento.',
      '13. Fico desorientado(a) ou em pânico em locais com poluição sonora ou muitas pessoas conversando ao mesmo tempo.',
      '14. Costumo fazer movimentos repetitivos com o corpo (como balançar) quando estou exposto(a) a ambientes cheios.',
      '15. Sinto que meu corpo demora para processar estímulos de temperatura (demorar para sentir frio ou calor intenso).',
    ],
    // === 12. ESCALA RAADS-R COMPLETA (25 perguntas fundamentais - Autismo Adulto) ===
    'Escala RAADS-R (Autismo Adulto)': [
      '1. Muitas vezes não sei se alguém está brincando ou falando sério em uma conversa.',
      '2. Eu prefiro conversar e focar em tópicos que envolvem fatos e lógica em vez de sentimentos.',
      '3. Tenho muita dificuldade em fazer pequenos diálogos sociais ou jogar conversa fora.',
      '4. Quando converso, tenho dificuldade em saber quando é a minha vez de falar ou ouvir.',
      '5. Costumo focar tanto nos pequenos detalhes que perco a visão do contexto geral das coisas.',
      '6. Tenho um interesse tão profundo por certos assuntos que posso falar sobre eles por horas.',
      '7. Sinto um incômodo físico ou dor real com barulhos comuns, luzes fortes ou certas texturas.',
      '8. Prefiro manter uma rotina idêntica e previsível todos os dias e mudo meu humor se houver imprevistos.',
      '9. Acho muito difícil mentir ou inventar desculpas sociais, sendo excessivamente direto(a).',
      '10. As pessoas frequentemente me dizem que falo de um jeito muito formal, monótono ou técnico.',
      '11. Tenho dificuldade crônica em manter ou iniciar amizades duradouras da minha idade.',
      '12. Costumo repetir gestos, balançar o corpo ou mexer nas mãos para me acalmar quando estou tenso(a).',
      '13. Sinto que preciso camuflar ou imitar os comportamentos dos outros para conseguir me encaixar.',
      '14. Prefiro fazer minhas refeições, passeios ou hobbies de forma isolada.',
      '15. Tenho dificuldade em decifrar o que as pessoas estão sentindo apenas olhando para as expressões delas.',
      '16. Muitas vezes levo comentários irônicos de forma literal e acabo me sentindo magoado(a).',
      '17. Sinto um esgotamento mental massivo após passar poucas horas em ambientes cheios de pessoas.',
      '18. Gosto de categorizar, listar ou organizar minhas coisas em ordens muito específicas.',
      '19. Tenho hipersensibilidade a tecidos, etiquetas de roupas ou texturas de certos alimentos.',
      '20. Sinto que passei a vida inteira agindo como um ator em um palco nas interações cotidianas.',
      '21. Tenho dificuldade em manter contato visual direto e confortável com meu interlocutor.',
      '22. Desenvolvo hiperfocos intensos por temas específicos que mudam completamente de tempos em tempos.',
      '23. Acho difícil compreender as regras sociais implícitas de convivência corporativa ou acadêmica.',
      '24. Prefiro interações diretas e textuais por mensagens do que ligações ou reuniões presenciais.',
      '25. Preciso de dias inteiros de silêncio e isolamento para recuperar minhas energias após interações.',
    ],

    // === 13. ESCALA WHODAS 2.0 COMPLETA (12 perguntas oficiais da OMS - Funcionalidade) ===
    'Escala WHODAS 2.0 (Funcionalidade OMS)': [
      '1. Quanta dificuldade você teve para ficar de pé por longos períodos (cerca de 30 minutos)?',
      '2. Quanta dificuldade você teve para cuidar das suas responsabilidades domésticas/de casa?',
      '3. Quanta dificuldade você teve para aprender uma nova tarefa (por exemplo, aprender um caminho novo)?',
      '4. Quanta dificuldade você teve para participar de atividades comunitárias, sociais ou de lazer?',
      '5. Quanta dificuldade você teve para lidar com o estresse provocado por mudanças na rotina?',
      '6. Quanta dificuldade você teve para manter a concentração em uma atividade por pelo menos 10 minutos?',
      '7. Quanta dificuldade você teve para caminhar distâncias longas (como um quarteirão ou 100 metros)?',
      '8. Quanta dificuldade você teve para realizar sua higiene pessoal (como tomar banho ou vestir-se)?',
      '9. Quanta dificuldade você teve para interagir e lidar com pessoas que você não conhece muito bem?',
      '10. Quanta dificuldade você teve para manter uma amizade ou relacionamento afetivo próximo?',
      '11. Quanta dificuldade você teve para realizar suas atividades diárias de trabalho ou estudos (na escola/EJA)?',
      '12. Quanto a sua saúde física ou emocional impactou ou limitou seus planos e metas nas últimas semanas?',
    ],

    // === 14. TRIAGEM DE IDEAÇÃO EROTOMANÍACA E APEGO BORDERLINE COMPLETO (10 perguntas) ===
    'Ideação Erotomaníaca e Apego Borderline': [
      '1. Nutre a crença fixa e intensa de que uma pessoa está secretamente apaixonada por você?',
      '2. Interpreta pequenos sinais casuais ou olhares de terceiros como declarações ocultas de amor ou interesse?',
      '3. Dedica grande parte do dia em tentativas de contato com essa pessoa, mesmo sem reciprocidade?',
      '4. Sente uma ansiedade desesperadora ou pânico diante da menor suspeita de rejeição?',
      '5. Costuma idealizar uma pessoa de forma extrema em um dia e, depois, passar a odiá-la profundamente?',
      '6. Cria cenários fantasiosos complexos de relacionamento amoroso com indivíduos com quem tem pouco ou nenhum vínculo real?',
      '7. Apresenta ciúme obsessivo, controlador ou possessivo que costuma afastar seus parceiros?',
      '8. Já realizou comportamentos de vigilância ou perseguição para monitorar a rotina de alguém?',
      '9. Sente um vazio interno crônico que tenta preencher fixando-se obsessivamente na atenção de uma única pessoa?',
      '10. Isola-se de suas obrigações diárias, familiares ou sociais para focar exclusivamente em pensamentos românticos?',
    ],
  }; // Fecha o mapa de perguntas de forma correta
} // Fecha a classe principal
