class EscalaAbc {
  static final List<Map<String, dynamic>> itens = [
    {'pergunta': '1. Gira em torno de si por longo período de tempo.', 'peso': 4},
    {'pergunta': '2. Aprende uma tarefa, mas esquece rapidamente.', 'peso': 2},
    {'pergunta': '3. É raro atender a estímulos não-verbais sociais/ambientais.', 'peso': 4},
    {'pergunta': '4. Ausência de resposta para solicitações verbais (parece surdo).', 'peso': 4},
    {'pergunta': '5. Sobressalta-se ou demonstra terror com ruídos cotidianos.', 'peso': 3},
    {'pergunta': '6. Flutuações severas de humor sem motivo aparente.', 'peso': 2},
    {'pergunta': '7. Apresenta maneirismos motores repetitivos (flapping).', 'peso': 4},
    {'pergunta': '8. Fixação visual em objetos que giram (ventiladores, rodas).', 'peso': 4},
    {'pergunta': '9. Evita ativamente o contato visual direto.', 'peso': 3},
    {'pergunta': '10. Apresenta reações extremas de isolamento social.', 'peso': 4},
    {'pergunta': '11. Usa os brinquedos de forma não-funcional.', 'peso': 3},
    {'pergunta': '12. Apresenta ecolalia imediata ou tardia.', 'peso': 3},
    {'pergunta': '13. Não responde quando é chamado pelo próprio nome.', 'peso': 2},
    {'pergunta': '14. Não imita gestos ou expressões faciais simples.', 'peso': 2},
    {'pergunta': '15. Prefere brincar sozinho do que interagir com outras crianças.', 'peso': 3},
    {'pergunta': '16. Demonstra rituais rígidos e inflexíveis no dia a dia.', 'peso': 3},
    {'pergunta': '17. Apego excessivo e incomum a objetos não convencionais.', 'peso': 3},
    {'pergunta': '18. Anda na ponta dos pés com frequência considerável.', 'peso': 2},
    {'pergunta': '19. Dificuldade extrema em aceitar novas texturas alimentares.', 'peso': 2},
    {'pergunta': '20. Apresenta crises de choro ou riso descontextualizadas.', 'peso': 2},
    {'pergunta': '21. Cheira ou lambe objetos e brinquedos de forma incomum.', 'peso': 2},
    {'pergunta': '22. Parece não sentir dor física mesmo em machucados sérios.', 'peso': 3},
    {'pergunta': '23. Reação de pânico ou agitação extrema em ambientes cheios.', 'peso': 3},
    {'pergunta': '24. Dificuldade em usar o pronome correto para se referir a si.', 'peso': 2},
    {'pergunta': '25. Apresenta inversão pronominal frequente na fala.', 'peso': 2},
    {'pergunta': '26. Não usa o dedo indicador para apontar interesse por algo.', 'peso': 3},
    {'pergunta': '27. Dificuldade severa em expressar sentimentos ou desejos.', 'peso': 2},
    {'pergunta': '28. Posturas corporais bizarras ou posições rígidas incomuns.', 'peso': 3},
    {'pergunta': '29. Demonstra fascinação por luzes brilhantes ou reflexos.', 'peso': 2},
    {'pergunta': '30. Apresenta movimentos oscilatórios de vaivém com o corpo.', 'peso': 4},
    {'pergunta': '31. Tem crises de birra intensas se interrompido em tarefas.', 'peso': 3},
    {'pergunta': '32. Alinhamento rígido ou enfileiramento obsessivo de brinquedos.', 'peso': 3},
    {'pergunta': '33. Demonstra falta de empatia ou percepção do perigo real.', 'peso': 3},
    {'pergunta': '34. Reações agressivas direcionadas a si mesmo (autoagressão).', 'peso': 4},
    {'pergunta': '35. Demonstra indiferença à presença de familiares próximos.', 'peso': 4},
    {'pergunta': '36. Apresenta interrupções e sobressaltos no padrão de sono.', 'peso': 2},
    {'pergunta': '37. Dificuldade em compreender metáforas ou piadas simples.', 'peso': 2},
    {'pergunta': '38. Usa a mão do adulto como uma ferramenta para obter objetos.', 'peso': 3},
    {'pergunta': '39. Apresenta hiperfoco em temas muito restritos e isolados.', 'peso': 3},
    {'pergunta': '40. Demonstra reações extremas a pequenas mudanças físicas na sala.', 'peso': 3},
    {'pergunta': '41. Vocalizações repetitivas e sons sem sentido funcional.', 'peso': 2},
    {'pergunta': '42. Recusa de contato físico espontâneo (abraços, toques).', 'peso': 3},
    {'pergunta': '43. Fixação por partes específicas de objetos (ex: rodinhas).', 'peso': 3},
    {'pergunta': '44. Apresenta atraso global no desenvolvimento da linguagem.', 'peso': 4},
    {'pergunta': '45. Não desenvolve jogos simbólicos (ex: escolinha, casinha).', 'peso': 3},
    {'pergunta': '46. Demonstra reações desproporcionais ao toque de roupas novas.', 'peso': 2},
    {'pergunta': '47. Dificuldade em imitar vocalizações de palavras simples.', 'peso': 2},
    {'pergunta': '48. Não compartilha experiências prazerosas com os pais.', 'peso': 3},
    {'pergunta': '49. Demonstra reações severas de medo a animais inofensivos.', 'peso': 2},
    {'pergunta': '50. Apresenta hipotonia muscular ou descoordenação motora ampla.', 'peso': 2},
    {'pergunta': '51. Dificuldade acentuada em desfraldar ou controle de esfíncters.', 'peso': 2},
    {'pergunta': '52. Demonstra riso histérico sem estímulo correspondente.', 'peso': 2},
    {'pergunta': '53. Apresenta ansiedade extrema antes de consultas médicas.', 'peso': 2},
    {'pergunta': '54. Fixação por texturas específicas como superfícies lisas.', 'peso': 2},
    {'pergunta': '55. Resiste ativamente a usar calçados ou andar descalço.', 'peso': 2},
    {'pergunta': '56. Apresenta reações de apego e choro intenso sem separação.', 'peso': 2},
    {'pergunta': '57. Repetição contínua de movimentos de pinça com os dedos.', 'peso': 3},
  ];
}
