class EscalaAbc {
  static const List<String> perguntas = [
    '1. Gira em torno de si por longo período de tempo.',
    '2. Aprende uma tarefa, mas esquece rapidamente.',
    '3. É raro atender a estímulos não-verbais sociais/ambientais.',
    '4. Ausência de resposta para solicitações verbais (parece surdo).',
    '5. Sobressalta-se ou demonstra terror com ruídos cotidianos.',
    '6. Flutuações severas de humor sem motivo aparente.',
    '7. Apresenta maneirismos motores repetitivos (flapping).',
    '8. Fixação visual em objetos que giram (ventiladores, rodas).',
    '9. Evita ativamente o contato visual direto.',
    '10. Apresenta reações extremas de isolamento social.',
    '11. Usa os brinquedos de forma não-funcional.',
    '12. Apresenta ecolalia imediata ou tardia.',
    '13. Não responde quando é chamado pelo próprio nome.',
    '14. Não imita gestos ou expressões faciais simples.',
    '15. Prefere brincar sozinho do que interagir com outras crianças.',
    '16. Demonstra rituais rígidos e inflexíveis no dia a dia.',
    '17. Apego excessivo e incomum a objetos não convencionais.',
    '18. Anda na ponta dos pés com frequência considerável.',
    '19. Dificuldade extrema em aceitar novas texturas alimentares.',
    '20. Apresenta crises de choro ou riso descontextualizadas.',
    '21. Cheira ou lambe objetos e brinquedos de forma incomum.',
    '22. Parece não sentir dor física mesmo em machucados sérios.',
    '23. Reação de pânico ou agitação extrema em ambientes cheios.',
    '24. Dificuldade em usar o pronome correto para se referir a si.',
    '25. Apresenta inversão pronominal frequente na fala.',
    '26. Não usa o dedo indicador para apontar interesse por algo.',
    '27. Dificuldade severa em expressar sentimentos ou desejos.',
    '28. Posturas corporais bizarras ou posições rígidas incomuns.',
    '29. Demonstra fascinação por luzes brilhantes ou reflexos.',
    '30. Apresenta movimentos oscilatórios de vaivém com o corpo.',
    '31. Tem crises de birra intensas se interrompido em tarefas.',
    '32. Alinhamento rígido ou enfileiramento obsessivo de brinquedos.',
    '33. Demonstra falta de empatia ou percepção do perigo real.',
    '34. Reações agressivas direcionadas a si mesmo (autoagressão).',
    '35. Demonstra indiferença à presença de familiares próximos.',
    '36. Apresenta interrupções e sobressaltos no padrão de sono.',
    '37. Dificuldade em compreender metáforas ou piadas simples.',
    '38. Usa a mão do adulto como uma ferramenta para obter objetos.',
    '39. Apresenta hiperfoco em temas muito restritos e isolados.',
    '40. Demonstra reações extremas a pequenas mudanças físicas na sala.',
    '41. Vocalizações repetitivas e sons sem sentido funcional.',
    '42. Recusa de contato físico espontâneo (abraços, toques).',
    '43. Fixação por partes específicas de objetos (ex: rodinhas).',
    '44. Apresenta atraso global no desenvolvimento da linguagem.',
    '45. Não desenvolve jogos simbólicos (ex: escolinha, casinha).',
    '46. Demonstra reações desproporcionais ao toque de roupas novas.',
    '47. Dificuldade em imitar vocalizações de palavras simples.',
    '48. Não compartilha experiências prazerosas com os pais.',
    '49. Demonstra reações severas de medo a animais inofensivos.',
    '50. Apresenta hipotonia muscular ou descoordenação motora ampla.',
    '51. Dificuldade acentuada em desfraldar ou controle de esfíncters.',
    '52. Demonstra riso histérico sem estímulo correspondente.',
    '53. Apresenta ansiedade extrema antes de consultas médicas.',
    '54. Fixação por texturas específicas como superfícies lisas.',
    '55. Resiste ativamente a usar calçados ou andar descalço.',
    '56. Apresenta reações de apego e choro intenso sem separação.',
    '57. Repetição contínua de movimentos de pinça com os dedos.'
  ];

  static const List<int> pesos = [
    4, 2, 4, 4, 3, 2, 4, 4, 3, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3, 2, 4, 3, 3, 3, 4, 4, 2, 2, 3, 3, 3, 2, 3, 3, 4, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3
  ];
}
